version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "설치"
      - cd server
      - npm install

  build:
    commands:
      - echo "빌드"
      - npm run build:

  post_build:
    commands:
      - echo "빌드 성공"
      
artifacts:
  files:
    - "dist/**"          # 빌드 결과물
    - "config/*.json"    # 설정 파일

cache:
  paths:
    - "node_modules/**/*"  # node_modules 캐싱