version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Moving to server directory..."
      - cd server  # server 폴더로 이동
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

  post_build:
    commands:
      - echo "Build complete!"

artifacts:
  files:
    - "server/dist/**"          # 빌드 결과물
    - "server/config/*.json"    # 설정 파일

cache:
  paths:
    - "server/node_modules/**/*"  # node_modules 캐싱
