version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20  # Docker 버전 설정
    commands:
      - echo "Installing dependencies..."
      - cd server
      - npm install --production  # 필요한 의존성만 설치

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-express-app .  # Docker 이미지 빌드
      - docker tag my-express-app:latest public.ecr.aws/n5i2p1p8/test/test  # ECR 태그 추가

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push public.ecr.aws/n5i2p1p8/test/test  # Docker 이미지 푸시

artifacts:
  files:
    - "server/dist/**"          # 빌드 결과물 (필요한 경우)

cache:
  paths:
    - "server/node_modules/**/*"  # node_modules 캐싱
